project_id = "ubqxlkvdbmkvtesmmwvj"

[functions.generate-tshirt-design]
verify_jwt = false

[functions.create-designer]
verify_jwt = false

[functions.convert-cloth-design]
verify_jwt = false

[functions.pattern-to-design]
verify_jwt = false
